### ISSUE TITLE
Image and target mismatching during generation

### ISSUE THREAD

**Issue by blaze1522** [oripress/CCC#3]
Hi authors,

Thank you for the much-needed baseline for CTTA setting for truly long-term continual test time adaptation. I was using your benchmark to evaluate my method for some review purposes. I found that the generation of targets and images for dataset is mismatched due to a subtle bug. [Solved]

```
class ApplyTransforms(data.Dataset):
    ...
    self.paths = all_paths
    self.paths = self.paths[:freq]
    all_classes = os.listdir(data_root)  # os.listdir() doesn't return lists in sorted order, rather it depends on how the files are indexed in 
                                         # the files system therefore it needs to be replaced by sorted(os.listdir(data_root))
    target_list = []
    for cur_path in self.paths:
        cur_class = cur_path.split("/")[-2]
        cur_class = all_classes.index(cur_class)
        target_list.append(cur_class)

    self.targets = target_list
    ...
```

If it is fine, I can create a pull request along with some other minor issues (possible system-specific issues to me) that you may or may not consider.

Thanks,

**Comment by oripress** [comment]
Thanks for informing us about this. I have added sorted(), as that is how it should be. 
Please don't hesitate to inform us of any further bugs. 
Thanks again.

**Comment by blaze1522** [comment]
Thank you :)

**Comment by blaze1522** [comment]
An issue similar to the above can be found in eval.py line 17

```
def get_webds_loader(dset_path):
    highest_ind = os.listdir(dset_path)[-1].split("_")[-1].replace(".tar", "")
    url = os.path.join(dset_path, "serial_{{00000..{}}}.tar".format(highest_ind))
```

Can be fixed by adding sorted.

**Comment by oripress** [comment]
Fixed as well, thanks again!
