### ISSUE TITLE
RPL implementation

### ISSUE THREAD

**Issue by tx-5** [oripress/CCC#7]
Hi, 
thank you very much for the great work. In your paper you write that RPL uses a student-teacher approach, but the teacher seems to be missing in the code. Did you generate the results with the code shown here or did you use a teacher? If you used a teacher, which momentum did you use for its updates? 0.999 like CoTTA?
Thank you very much and kind regards
TX-5

**Comment by tx-5** [comment]
Sorry to bother you again, but in your paper you write in section 4 "Following the original implementations, Tent, ETA, EATA and RDumb use SGD with a learning rate of 2.5*10-5. RPL uses SGD with a learning rate of 5*10-3.". In your code, the default learning rates are 2.5*10-4 and 5*10-4. I assume the latter are the correct ones as they correspond to the original implementations?

**Comment by oripress** [comment]
Yep, the code is correct, will fix the paper. Thanks for pointing this out, please feel free to reach out if you catch any other errors :)
