### ISSUE TITLE
Adding new method SANTA

### ISSUE THREAD

**Issue by goirik-chakrabarty** [oripress/CCC#8]
Hi authors,

Thank you for your excellent work in benchmarking test-time adaptation. I am the author of SANTA [https://openreview.net/forum?id=V7guVYzvE4]. I came across your benchmark during the review process and used it. I would like to add my method to your benchmark.

What are the proper steps to submit a pull request?

Regards

**Comment by oripress** [comment]
Hi!
Sorry, we currently don't maintain a leaderboard. 
Cool paper!
