### ISSUE TITLE
Webdataset streaming abruptly terminates

### ISSUE THREAD

**Issue by Riddhiman-M** [oripress/CCC#9]
Hello,

Thanks for the great work. I faced an issue while streaming CCC from the cloud (the connection seems to be reset intermediately, despite having a stable connection on our end). Could this have been due to a server-side problem (I've tried streaming this multiple times but every time the streaming is interrupted after a few 1000 batches or so)? Do you have any pointers on how this could be resolved?
<img width="681" alt="CCC_image1" src="https://github.com/oripress/CCC/assets/89708853/bbdf8acc-0657-432c-ae04-027976c4bca1">
<img width="681" alt="image (2)" src="https://github.com/oripress/CCC/assets/89708853/9f1517ba-0128-43f6-b4f5-4638634980db">

**Comment by oripress** [comment]
We're currently looking into this, but as this is a problem with our cloud, it could take a while to resolve. If this only happens on a certain baseline accuracy/speed/seed combination, you might want to generate only that combination for the time being.

**Comment by Riddhiman-M** [comment]
Sure thanks for addressing this. I'll explore alternative baseline-speed-seed configurations in the meantime.

**Comment by waychin-weiqin** [comment]
Hi, 

I am wondering if this issue has been resolved. I am facing the same problem. Any guidance on how to resolve this issue would be appreciated! 

Thank you :)

**Comment by oripress** [comment]
Small update: I'm back on trying to fix this issue, I hope to have a positive answer soon, but it is somewhat out of my control. I will update here once more when I get more information.

**Comment by oripress** [comment]
I think I've resolved the issue. 
In eval.py, there seems to be an issue when `num_workers` is greater than 0 in the dataloader. 
I've also reuploaded all files, and it seems to work.

**Comment by waychin-weiqin** [comment]
Hi, thank you for addressing the issue. I have a quick question about the dataset: Does every configuration contain 99,999 tar files, or does the number of files vary depending on the specific dataset?

For example, in the URL format below: url = f'https://mlcloud.uni-tuebingen.de:7443/datasets/CCC/{dset_name}/serial_{{00000..99999}}.tar'

When I run the evaluation script, I'm only able to download around 800 tar files before an error occurs and the process is interrupted. Could you please clarify this?

Thanks again for your help :)

**Comment by oripress** [comment]
The 99999 is just a placeholder -- there should be around 900 files for speeds 1k and 5k, and around 300 files for 2k. I think this is dependent on the compression by WebDataset, but the important thing is that there are 7.5M images total in each run.
